const express = require("express");
const cors = require("cors");
const path = require("path");
const db = require("./db");
require("dotenv").config();
const app = express();
app.use(cors());
app.use(express.json({ limit: "200kb" }));
app.use(express.static(path.join(__dirname, "public")));
app.use(express.static(__dirname));
const cargo = body => (body && (body.cargo || (body.usuario && body.usuario.cargo))) || "Usuário";
const isStaff = body => ["ADM", "Assistente"].includes(cargo(body));
const isAdmin = body => cargo(body) === "ADM";
function error(res, err, fallback) { console.error(err.message); res.status(err.code === "23505" ? 409 : (err.status || 500)).json({ erro: err.code === "23505" ? "Este email já está cadastrado!" : (err.message || fallback) }); }
app.get("/teste-banco", (req,res) => res.json({ conectado: db.isOnline(), modo: db.isOnline() ? "postgres" : "fallback-json" }));
app.get("/usuarios", async (req,res) => { try { res.json(await db.usuarios()); } catch(e) { error(res,e,"Erro ao listar usuários."); } });
app.post("/cadastro", async (req,res) => { try { res.status(201).json({ sucesso:true, usuario:await db.createUsuario(req.body) }); } catch(e) { error(res,e,"Erro no cadastro."); } });
app.post("/login", async (req,res) => { try { const usuario=await db.login(req.body.email,req.body.senha); res.json(usuario ? {sucesso:true,usuario} : {sucesso:false,erro:"E-mail ou senha incorretos."}); } catch(e) { error(res,e,"Erro no login."); } });
app.delete("/usuarios/:id", async (req,res) => { try { if(!isAdmin(req.body)) return res.status(403).json({erro:"Apenas ADM pode excluir contas."}); res.json({sucesso:!!(await db.deleteUsuario(req.params.id))}); } catch(e) { error(res,e,"Erro ao excluir usuário."); } });
app.get("/recados", async (req,res) => { try { res.json(await db.recados()); } catch(e) { error(res,e,"Erro ao carregar recados."); } });
app.post("/recados", async (req,res) => { try { res.status(201).json({sucesso:true,recado:await db.createRecado(req.body)}); } catch(e) { error(res,e,"Erro ao salvar recado."); } });
app.delete("/recados/:id", async (req,res) => { try { if(!isStaff(req.body)) return res.status(403).json({erro:"Sem permissão para excluir recados."}); res.json({sucesso:!!(await db.deleteRecado(req.params.id))}); } catch(e) { error(res,e,"Erro ao excluir recado."); } });
app.get("/favoritos/:usuario_id", async (req,res) => { try { res.json(await db.favoritos(req.params.usuario_id)); } catch(e) { error(res,e,"Erro ao carregar favoritos."); } });
app.post("/favoritos", async (req,res) => { try { res.status(201).json({sucesso:true,favorito:await db.createFavorito(req.body)}); } catch(e) { error(res,e,"Erro ao salvar favorito."); } });
app.delete("/favoritos/:usuario_id/:id", async (req,res) => { try { res.json({sucesso:!!(await db.deleteFavorito(req.params.usuario_id,req.params.id))}); } catch(e) { error(res,e,"Erro ao excluir favorito."); } });
app.get("/", (req,res) => res.sendFile(path.join(__dirname,"public","index.html")));
const port=process.env.PORT||3000; app.listen(port,"0.0.0.0",()=>console.log("Servidor rodando na porta "+port));
